config/routes.rb
Rails.application.routes.draw do

  
  resources :rent_payments
  resources :permission_items
  resources :features
  resources :currencies
  resources :expenses do 
    get "delete"
  end
  resources :incomes do 
    get "delete"

    collection do  
        get "get_property_rent" => "incomes#get_property_rent"

    end

  end
  
  resources :payments do 
    get "delete"
  end
  
  resources :taxes do 
    get "delete"
  end
  resources :organizations do 
    get "delete"
  end
  resources :handovers do 
    get "delete"
  end
  resources :leases do 
    get "delete"

    collection do  
        get "get_available_properties" => "leases#get_available_properties"
        get "get_property_rent" => "leases#get_property_rent"
        get "get_properties_by_type" => "leases#get_properties_by_type"


    end
  end
  resources :mandates do 
    get "delete"

    collection do  
        get "get_properties" => "mandates#get_properties"
        get "get_properties_by_type" => "mandates#get_properties_by_type"

        get "get_property_rent" => "mandates#get_property_rent"

    end
    
  end

  resources :properties do 
    get "delete"
    
    collection do  
        get "get_landlord" => "properties#get_landlord"
        #get "get_prestation_amount" => "receipts#get_prestation_amount"

    end
    
  end
  resources :buildings do 
    get "delete"
  end
  resources :cities do 
    get "delete"
  end
  resources :tenants do 
    get "delete"
  end
  resources :landlords do 
    get "delete"
  end
  resources :landlord_types do 
    get "delete"
  end
  resources :tenant_types do 
    get "delete"
  end
  resources :property_types do 
    get "delete"
  end
  resources :profiles do 
    get "delete"
  end
  resources :services do 
    get "delete"
  end
  #devise_for :users
  resources :permissions do 
    get "delete"
  end
  resources :roles do 
    get "delete"
  end
  


  get "/dashboard" => "dashboard#index" , as: :dashboard
  get "/users"     => "custom_users#index", as: :all_users 
  get "/users/unregistered"     => "custom_users#unregistered", as: :unregistered_commission_percentage 
  post "/users/new"     => "custom_users#create", as: :create_user
  get "/users/new"     => "custom_users#new", as: :new_user
  get "/user/edit/:id" => "custom_users#edit", as: :edit_user
  patch "/user/update/:id" => "custom_users#update", as: :update_user
  delete "/user/destroy/:id" => "custom_users#destroy", as: :destroy_user
  get "/user/delete/:id" => "custom_users#delete", as: :delete_user
  
  get "/setup/admin" => "admin_setup#new", as: :new_admin
  post "/setup/admin/create" => "admin_setup#create", as: :create_admin


  get "/user/enable/:id" => "custom_users#get_enable", as: :get_enable_user_account
  post "/user/enable/:id" => "custom_users#post_enable", as: :post_enable_user_account
  get "/user/disable/:id" => "custom_users#get_disable", as: :get_disable_user_account
  post "/user/disable/:id" => "custom_users#post_disable", as: :post_disable_user_account


  devise_for :users, path: '', controllers: { 
    registrations: "users/registrations",
    confirmations: 'users/confirmations',
    passwords: "users/passwords",
    sessions: "users/sessions"
        
    }, 
    path_names: {
        sign_in: 'login', 
        sign_out: 'logout', 
        password: 'secret', 
        confirmation: 'verification', 
        unlock: 'unblock', 
        registration: 'signup', 
        sign_up: '' 
    }
   
    devise_scope :user do
      root to: "users/sessions#new"
      authenticated :user do
        root 'dashboard#index', as: :authenticated_root
      end
  
      unauthenticated do
        root 'users/sessions#new', as: :unauthenticated_root
      end
    end


    # Dynamic error pages
    get "/404", to: "errors#not_found"
    get "/422", to: "errors#unacceptable"
    get "/500", to: "errors#internal_error"


end

app/controllers/custom_users_controller.rb
class CustomUsersController < ApplicationController
		before_action :authenticate_user!
		layout "dashboard"

    before_action :set_user, only: [:show, :edit, :update, :destroy] # probably want to keep using this
    
    

    
		def new
			@services = Service.all
			@roles = Role.where.not(name: ["superuser", "root"])
			@user = User.new
			@user.build_profile
		
			
		end
	
    def create
		@user = User.new(user_params)
		#@user.created_by = current_user.id

			respond_to do |format|
				if @user.save
					#@user.build_profile
					@users = User.where.not(id: current_user.id)

					format.html { redirect_to all_users_path, notice: 'User was successfully created.' }
					format.json { render :show, status: :created, location: @contributor }
					format.js
		

			
			
				else
					format.html { render :new }
					format.json { render json: @user.errors, status: :unprocessable_entity }
					format.js
				end
			end
		end
		
		def create_admin
		end

	# Index
    def index
    	
			@users = User.where.not(id: current_user.id)
		
	
    end
    
    def unregistered
     
    end
	
    # GET /users/1
    # GET /users/1.json
	def show
		
    end

    # GET /users/1/edit
		def edit
			@services = Service.all
			@roles = Role.where.not(name: "superuser")
			@user.profile || @user.build_profile 
    end

    def delete
    	@user = User.find(params[:id])
    end

    def get_disable
        @user = User.find(params[:id]) if params[:id].present?
     
	end
	
    def post_disable
	  	@user = User.find(params[:id]) if params[:id].present?
	  
      	respond_to do |format|
        	if @user.update_attributes(status: 'disable')
						@users = User.where.not(id: current_user.id)
        
				format.html { redirect_to @user, notice: 'User was successfully updated.' }
				format.json { render :show, status: :ok, location: @user }
				format.js
        
				# Send mail to user.
				#url = user_session_url
				#UserMailer.disable_user_mail(@user.email, @user.password, url).deliver_now
			else
				format.html { render :edit }
				format.json { render json: @user.errors, status: :unprocessable_entity }
				format.js
			end
		end
   
    end

    def get_enable
    	@user = User.find(params[:id]) if params[:id].present?
   
	end
	
	# Enable user account.
  	def post_enable
		@user = User.find(params[:id]) if params[:id].present?
		respond_to do |format|
      		if @user.update_attributes(status: 'enable')
						@users = User.where.not(id: current_user.id)
			
				format.html { redirect_to @user, notice: 'User was successfully updated.' }
				format.json { render :show, status: :ok, location: @user }
				format.js
      
				

				Thread.new do
					Rails.application.executor.wrap do
					  # your code here
					end
				  end
			  
			else
				format.html { render :edit }
				format.json { render json: @user.errors, status: :unprocessable_entity }
				format.js
			end
      	end
 
  	end

    

	def destroy
    	@users = User.all
    
    	if @user.destroy
				@users = User.where.not(id: current_user.id)

				respond_to do |format|
					format.html { redirect_to all_users_path, notice: "L'utilisateur a été supprimer avec succès!" }
					format.json { head :no_content }
					format.js
			
					
			
				end
		end

 	end

   	

    # # PATCH/PUT /users/1
    # # PATCH/PUT /users/1.json
    def update
		respond_to do |format|
			
			if params[:user][:password].blank? #&& params[:user][:password_confirmation].blank?
				params[:user].delete(:password)
				params[:user].delete(:password_confirmation)
			end

			if @user.update(user_params)
				@users = User.where.not(id: current_user.id)

				format.html { redirect_to all_users_path, notice: 'User was successfully updated.' }
				format.json { render :show, status: :ok, location: @user }
				format.js
			

	
				  
				
			else
				format.html { render :edit }
				format.json { render json: @user.errors, status: :unprocessable_entity }
				format.js
			end
      	end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
     
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password,:password_confirmation, :role_id, :service_id,  profile_attributes: [:first_name, :last_name, :civility])
    end

end

app/views/custom_users/_after_disable.js.erb
$("ul.errors").html("");
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"));
  <% end %>
<% else %>
  $(".users").html("<%= escape_javascript(render 'index') %>");
  $("#user-disable-modal").modal("hide");
 
<% end %>

app/views/custom_users/_after_enable.js.erb
$("ul.errors").html("");
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"));
  <% end %>
<% else %>
  $(".users").html("<%= escape_javascript(render 'index') %>");
  $("#user-enable-modal").modal("hide");
 
<% end %>

app/views/custom_users/_create.js.erb
$("ul.errors").html("");
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"));
  <% end %>
<% else %>
  $(".users").html("<%= escape_javascript(render 'index') %>");
  $("#user-modal").modal("hide");
 
<% end %>

app/views/custom_users/_form.html.erb
<%= form_with(model: user, url: (user.new_record? ? create_user_path : update_user_path), local: false) do |f| %>
		<div class="modal-body">
		 	<ul class="errors">
    		</ul>
			
				
			<%= f.fields_for :profile do |p| %>
				<!-- Fieldset informations -->
				<fieldset>
					<legend>Informations </legend>
					<div class="row">

                        <div class="form-group col-md-4">
                            <%= p.label "Prénom" %>
                            <%= p.text_field :first_name, class: "form-control", placeholder: "Prénom", required: true %>
                        </div>

                        <div class="form-group col-md-4">
                            <%= p.label "Nom" %>
                            <%= p.text_field :last_name , class: "form-control", placeholder: "Nom" , required: true%>
                        </div>
						

					
                        <div class="form-group col-md-4">
							<%= p.label :civility, "Civilité", class: "required" %> 
							<%= p.select :civility , CIVILITIES, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%" , required: true %>
						
						</div>
					</div>

                    
				</fieldset>
			<% end %>

			
			
			<div class="row">
				<div class="col-md-6 form-group">
					<%= f.label "Service" %>
					<%= f.collection_select(:service_id, @services,  :id, :name , {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%;", required: true) %>
											
				</div>
				<div class="col-md-6 form-group">
					<%= f.label "Profil" %>
					<%= f.collection_select(:role_id, @roles,  :id, :name , {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%;", required: true) %>
											
				</div>
			</div>
			<div class="form-group">
				<%= f.label :email %>
				<%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", placeholder: "E-mail", required: true %>
			</div>

			<div class="row">
				<div class="col-md-6 form-group">
					<%= f.label :password %>
					<% if @minimum_password_length %>
					<em>(<%= @minimum_password_length %> characters minimum)</em>
					<% end %><br />
					<%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Mot de passe", required: true %>
				</div>
			
				<div class="col-md-6 form-group">
					<%= f.label :password_confirmation %><br />
					<%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control", placeholder: "Confirmation du mot de passe", required: true %>
				</div>
			</div>
				
		</div><!-- modal body -->
	<div class="modal-footer">
		<%= link_to "Annuler", "#", class: "btn btn-secondary tx-mont tx-medium tx-11 tx-uppercase pd-y-12 pd-x-25 tx-spacing-1", data: {dismiss: "modal"} %>
		<%= f.submit  class: "btn btn-primary tx-mont tx-medium tx-11 tx-uppercase pd-y-12 pd-x-25 tx-spacing-1",  "data-loading-text"=>"Loading...", autocomplete: "off" %>
	</div>
<% end %>

app/views/custom_users/_get_disable.html.erb
<!-- Modal -->

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Désactivation</h4>
      </div>
      	<div class="modal-body">
  <ul class="errors"></ul>
  Etes-vous sûr de vouloir désactiver le compte de cet utilisateur?
  <p>
  E-mail: <b> <%= @user.email %></b>
  </p>
  </div>
  <div class="modal-footer">
    <%= link_to "Annuler", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
    <%= link_to "Oui, désactiver", post_disable_user_account_path(@user), method: :post, remote: true, class: "btn btn-danger" %>
  </div>
  </div>
</div>

app/views/custom_users/_get_enable.html.erb
<!-- Modal -->

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Activation</h4>
      </div>
      	<div class="modal-body">
  <ul class="errors"></ul>
  Etes-vous sûr de vouloir activer le compte de cet utilisateur?
  <p>
  E-mail: <b> <%= @user.email %></b>
  </p>
  </div>
  <div class="modal-footer">
    <%= link_to "Annuler", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
    <%= link_to "Oui, activer", post_enable_user_account_path(@user), method: :post, remote: true, class: "btn btn-danger" %>
  </div>
  </div>
</div>

app/views/custom_users/_index.html.erb
<% if @users.present? %>
	<% @users.each do |user| %>
		<tr>
			
			<td><%= user.email %></td>
			<td><%= role_name(user.role_id) %></td>
			<td>
			<div class="action-buttons">
				<%= link_to raw('<i class="fa fa-pencil" aria-hidden="true"></i>
'), edit_user_path(user), title: "Modifier", remote: true %>


<% if is_account_locked?(user) %>
	<%= link_to raw('<i class="fa fa-ban" aria-hidden="true"></i>
	'), get_enable_user_account_path(user.id), remote: true, title: "Compte inactif. Cliquez pour l'activé", class: "delete" %>
<% else %>
<%= link_to raw('<i class="fa fa-check-circle" aria-hidden="true"></i>
	'),  get_disable_user_account_path(user.id), remote: true, title: "Compte actif. Cliquez pour le désactivé", class: "delete" %>
<% end %>

<%= link_to raw('<i class="fa fa-trash-o" aria-hidden="true"></i>
'), delete_user_path(user), remote: true, title: "Supprimer", class: "delete" %>
</div>
</td>

			  </tr>
			<% end %>
			<% end %>

app/views/custom_users/_new.html.erb
<!-- Modal -->

  <div class="modal-dialog modal-lg">
    <div class="modal-content ">
      <div class="modal-header pd-y-20 pd-x-25">
            <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">Nouvel - Utilisateur</h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

    <%= render 'form', user: @user %>
</div>
  </div>

app/views/custom_users/destroy.js.erb
<%= render "create" %>

app/views/custom_users/index.html.erb
<div class="br-pageheader">
      <nav class="breadcrumb pd-0 mg-0 tx-12">
        
        <span class="breadcrumb-item active"><h5>Utilisateurs</h2></span>
      </nav>
    </div><!-- br-pageheader -->
<div class="br-pagebody">
  <div class="br-section-wrapper">
    <div class="headers mg-b-20">
        <div class="left-content">
        </div>

        <div class="text-right">
            <%= link_to raw('<i class="fa fa-plus" aria-hidden="true"></i> Ajouter'), new_user_path, class: "btn btn-primary tx-mont tx-medium tx-11 tx-uppercase pd-y-12 pd-x-25 tx-spacing-1", remote: true %>

        </div>

    </div>


<table id="datatable1" class="table display responsive nowrap">
		  <thead>
			<tr>
			
				<th>E-mail</th>
				<th>Profil</th>
				<th>Actions</th>
			  
			</tr>
		  </thead>

		  <tbody class="users">
				<%= render('index') %>
		  </tbody>
		</table>
	</div>
</div>
<div id="user-modal" class="c-modal modal fade" data-backdrop="static"></div>

app/views/custom_users/new.js.erb
$("#user-modal").html("<%= escape_javascript(render 'new') %>");
$("#user-modal").modal("show");

app/views/custom_users/post_disable.js.erb
<%= render "after_disable" %>

app/views/custom_users/post_enable.js.erb
<%= render "after_enable" %>

app/views/custom_users/update.js.erb
<%= render "create" %>