config/routes.rb
Rails.application.routes.draw do

  
  resources :rent_payments
  resources :permission_items
  resources :features
  resources :currencies
  resources :expenses do 
    get "delete"
  end
  resources :incomes do 
    get "delete"

    collection do  
        get "get_property_rent" => "incomes#get_property_rent"

    end

  end
  
  resources :payments do 
    get "delete"
  end
  
  resources :taxes do 
    get "delete"
  end
  resources :organizations do 
    get "delete"
  end
  resources :handovers do 
    get "delete"
  end
  resources :leases do 
    get "delete"

    collection do  
        get "get_available_properties" => "leases#get_available_properties"
        get "get_property_rent" => "leases#get_property_rent"
        get "get_properties_by_type" => "leases#get_properties_by_type"


    end
  end
  resources :mandates do 
    get "delete"

    collection do  
        get "get_properties" => "mandates#get_properties"
        get "get_properties_by_type" => "mandates#get_properties_by_type"

        get "get_property_rent" => "mandates#get_property_rent"

    end
    
  end

  resources :properties do 
    get "delete"
    
    collection do  
        get "get_landlord" => "properties#get_landlord"
        #get "get_prestation_amount" => "receipts#get_prestation_amount"

    end
    
  end
  resources :buildings do 
    get "delete"
  end
  resources :cities do 
    get "delete"
  end
  resources :tenants do 
    get "delete"
  end
  resources :landlords do 
    get "delete"
  end
  resources :landlord_types do 
    get "delete"
  end
  resources :tenant_types do 
    get "delete"
  end
  resources :property_types do 
    get "delete"
  end
  resources :profiles do 
    get "delete"
  end
  resources :services do 
    get "delete"
  end
  #devise_for :users
  resources :permissions do 
    get "delete"
  end
  resources :roles do 
    get "delete"
  end
  


  get "/dashboard" => "dashboard#index" , as: :dashboard
  get "/users"     => "custom_users#index", as: :all_users 
  get "/users/unregistered"     => "custom_users#unregistered", as: :unregistered_commission_percentage 
  post "/users/new"     => "custom_users#create", as: :create_user
  get "/users/new"     => "custom_users#new", as: :new_user
  get "/user/edit/:id" => "custom_users#edit", as: :edit_user
  patch "/user/update/:id" => "custom_users#update", as: :update_user
  delete "/user/destroy/:id" => "custom_users#destroy", as: :destroy_user
  get "/user/delete/:id" => "custom_users#delete", as: :delete_user
  
  get "/setup/admin" => "admin_setup#new", as: :new_admin
  post "/setup/admin/create" => "admin_setup#create", as: :create_admin


  get "/user/enable/:id" => "custom_users#get_enable", as: :get_enable_user_account
  post "/user/enable/:id" => "custom_users#post_enable", as: :post_enable_user_account
  get "/user/disable/:id" => "custom_users#get_disable", as: :get_disable_user_account
  post "/user/disable/:id" => "custom_users#post_disable", as: :post_disable_user_account


  devise_for :users, path: '', controllers: { 
    registrations: "users/registrations",
    confirmations: 'users/confirmations',
    passwords: "users/passwords",
    sessions: "users/sessions"
        
    }, 
    path_names: {
        sign_in: 'login', 
        sign_out: 'logout', 
        password: 'secret', 
        confirmation: 'verification', 
        unlock: 'unblock', 
        registration: 'signup', 
        sign_up: '' 
    }
   
    devise_scope :user do
      root to: "users/sessions#new"
      authenticated :user do
        root 'dashboard#index', as: :authenticated_root
      end
  
      unauthenticated do
        root 'users/sessions#new', as: :unauthenticated_root
      end
    end


    # Dynamic error pages
    get "/404", to: "errors#not_found"
    get "/422", to: "errors#unacceptable"
    get "/500", to: "errors#internal_error"


end

app/models/handover.rb
# == Schema Information
#
# Table name: handovers
#
#  id               :bigint           not null, primary key
#  handover_type    :string
#  reference        :string
#  property_id      :integer
#  lease_id         :bigint
#  doors            :string
#  windows          :string
#  wall_cover       :string
#  flooring         :string
#  ventilators      :string
#  air_conditioners :string
#  light_bulbs      :string
#  faucets          :string
#  showers          :string
#  doorbell         :string
#  ceiling          :string
#  electricity      :string
#  notes            :text
#  user_id          :bigint
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Handover < ApplicationRecord
  include SharedUtils::Generate

  before_save :generate_random_number_uid
  
  belongs_to :lease
  belongs_to :user


  validates :lease_id, presence: true
  validates :handover_type, presence: true
  validates_with LeasePropertyValidator
  

end

app/controllers/handovers_controller.rb
class HandoversController < ApplicationController
  before_action :authenticate_user!
  before_action :set_handover, only: [:show, :edit, :update, :destroy]
  layout "dashboard"

  
  # GET /handovers
  # GET /handovers.json
  def index
    @handovers = Handover.all
  end

  # GET /handovers/1
  # GET /handovers/1.json
  def show
  end

  # GET /handovers/new
  def new
    @properties = Property.unavailable
    @handover = Handover.new
  end

  # GET /handovers/1/edit
  def edit
    @properties = Property.unavailable
  end

  # POST /handovers
  # POST /handovers.json
  def create
    @handover = current_user.handovers.build(handover_params)

    lease = Lease.find_by(property_id: @handover.property_id, status: "enable")

    if lease.present?
      @handover.lease_id = lease.id
    end

    respond_to do |format|
      if @handover.save
        @handovers = Handover.all
        format.html { redirect_to @handover, notice: 'Handover was successfully created.' }
        format.json { render :show, status: :created, location: @handover }
        format.js
      else
        format.html { render :new }
        format.json { render json: @handover.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /handovers/1
  # PATCH/PUT /handovers/1.json
  def update
    respond_to do |format|
      if @handover.update(handover_params)
        @handovers = Handover.all

        format.html { redirect_to @handover, notice: 'Handover was successfully updated.' }
        format.json { render :show, status: :ok, location: @handover }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @handover.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end


  def delete
    @handover = Handover.find(params[:handover_id])
  end


  # DELETE /handovers/1
  # DELETE /handovers/1.json
  def destroy
    @handover.destroy
    respond_to do |format|
      format.html { redirect_to handovers_url, notice: 'Handover was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_handover
      @handover = Handover.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def handover_params
      params.require(:handover).permit(:handover_type, :reference, :property_id,  :doors, :windows, :wall_cover, :flooring, :ventilators, :air_conditioners, :light_bulbs, :faucets, :showers, :doorbell, :ceiling, :electricity, :notes)
    end
end

app/helpers/handovers_helper.rb
module HandoversHelper
end

app/views/handovers/_create.js.erb
$("ul.errors").html("");
<% if @handover.errors.any? %>
  <% @handover.errors.full_messages.each do |message| %>
 
    $("ul.errors").append($('<div class="c-alert c-alert--danger" > ').html("<%= message.html_safe %> "));
  <% end %>
<% else %>
  $(".handovers").html("<%= escape_javascript(render 'index') %>");
  $("#handover-modal").modal("hide");
 
<% end %>

app/views/handovers/_delete.html.erb
<!-- Modal -->

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header pd-y-20 pd-x-25">
            <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">Suppression</h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
      	<div class="modal-body">
  <ul class="errors"></ul>
  Etes-vous sûr de vouloir supprimer cet enregistrement?
  <p>
  ID: <b> <%= @handover.id %></b>
  </p>
  </div>
  <div class="modal-footer">
    <%= link_to "Non", "#", class: "btn btn-secondary tx-mont tx-medium tx-11 tx-uppercase pd-y-12 pd-x-25 tx-spacing-1", data: { dismiss: "modal" } %>
    <%= link_to "Oui", handover_path(@handover), method: :delete, remote: true, class: "btn btn-danger tx-mont tx-medium tx-11 tx-uppercase pd-y-12 pd-x-25 tx-spacing-1" %>
  </div>
  </div>
</div>

app/views/handovers/_edit.html.erb
<!-- Modal -->

  <div class="modal-dialog modal-lg">
    <div class="modal-content ">
      <div class="modal-header pd-y-20 pd-x-25">
            <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">Modification - Etat des lieux</h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

           <%= render 'form', handover: @handover %>
    </div>
  </div>

app/views/handovers/_form.html.erb
<%= form_with(model: handover, local: false) do |form| %>
  
<div class="modal-body">
  
        <ul class="errors">
        </ul>
 
   <div class="row">
    

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :handover_type, "Type", class: "required" %>
         <%= form.select :handover_type, HANDOVER_TYPES, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%;" %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :property_id, "Propriéte", class: "required" %>
        <%= form.collection_select(:property_id, @properties, :id, :reference, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%;",  required: true) %> 
      </div>
    </div>


  </div>

  <div class="row">
    <div class="col-md">
      <div class="form-group">
        <%= form.label :reference, "Référence" %>
        <%= form.text_field :reference, class: "form-control", placeholder: "Référence" %>
      </div>
    </div>
  </div>

  <div class="row">

    <div class="col-md-3">
      <div class="form-group">
        <%= form.label :doors, "Portes" %>
        <%= form.select :doors, HANDOVER_STATUSES, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%;" %>
      </div>
    </div>


    <div class="col-md-3">
      <div class="form-group">
        <%= form.label :windows, "Fenêtres" %>
        <%= form.select :windows, HANDOVER_STATUSES, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%;" %>
      </div>
    </div>

    <div class="col-md-3">
      <div class="form-group">
        <%= form.label :wall_cover , "Revêtement mural"%>
        <%= form.select :wall_cover, HANDOVER_STATUSES, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%;" %>
      </div>
    </div>

    <div class="col-md-3">
      <div class="form-group">
        <%= form.label :flooring, "Revêtement de sol" %>
        <%= form.select :flooring, HANDOVER_STATUSES, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%;" %>
      </div>
    </div>
  </div>

  

  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <%= form.label :ventilators, "Ventilateurs" %>
        <%= form.select :ventilators, HANDOVER_STATUSES, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%;" %>
      </div>
    </div>

    <div class="col-md-3">

      <div class="form-group">
        <%= form.label :air_conditioners, "Climatisation" %>
        <%= form.select :air_conditioners, HANDOVER_STATUSES, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%;" %>
      </div>
    </div>

    <div class="col-md-3">

      <div class="form-group">
        <%= form.label :light_bulbs, "Ampoules" %>
        <%= form.select :light_bulbs, HANDOVER_STATUSES, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%;" %>
      </div>
    </div>

    <div class="col-md-3">

      <div class="form-group">
        <%= form.label :faucets , "Robinets"%>
        <%= form.select :faucets, HANDOVER_STATUSES, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%;" %>
      </div>
    </div>

  </div>

  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <%= form.label :showers, "Docuhes" %>
        <%= form.select :showers, HANDOVER_STATUSES, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%;" %>
      </div>
    </div>

    <div class="col-md-3">
      <div class="form-group">
        <%= form.label :doorbell, "Sonnette" %>
        <%= form.select :doorbell, HANDOVER_STATUSES, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%;" %>
      </div>
    </div>

    <div class="col-md-3">
      <div class="form-group">
        <%= form.label :ceiling, "Plafond" %>
        <%= form.select :ceiling, HANDOVER_STATUSES, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%;" %>
      </div>
    </div>

    <div class="col-md-3">

      <div class="form-group">
        <%= form.label :electricity, "Electricité" %>
        <%= form.select :electricity, HANDOVER_STATUSES, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%;" %>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-md-12">

      <div class="form-group">
        <%= form.label :notes, "Notes" %>
        <%= form.text_area :notes, class: "form-control", placeholder: "Notes" %>
      </div>
    </div>
  </div>

  
</div><!-- modal body -->
     <div class="modal-footer">
            <%= link_to "Annuler", "#", class: "btn btn-secondary tx-mont tx-medium tx-11 tx-uppercase pd-y-12 pd-x-25 tx-spacing-1", data: {dismiss: "modal"} %>
            <%= form.submit "Enregistrer", class: "btn btn-primary tx-mont tx-medium tx-11 tx-uppercase pd-y-12 pd-x-25 tx-spacing-1",  "data-loading-text"=>"Loading...", autocomplete: "off" %>
    </div>
<% end %>

app/views/handovers/_index.html.erb
<% @handovers.each do |handover| %>
      <tr>
        <td><%= handover.id %></td>
        <td><%= handover.created_at.strftime("%d/%m/%Y") %></td>
        <td><%= property(handover.property_id).reference %></td>
        <td><%= handover.handover_type %></td>
        <td><%= handover.reference %></td>
       
        
        <td><%= link_to 'Show', handover %></td>
        <td><%= link_to 'Edit', edit_handover_path(handover) %></td>
        <td><%= link_to 'Destroy', handover, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

app/views/handovers/_new.html.erb
<!-- Modal -->

  <div class="modal-dialog modal-lg">
    <div class="modal-content ">
      <div class="modal-header pd-y-20 pd-x-25">
            <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">Nouveau - Etat des lieux</h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

           <%= render 'form', handover: @handover %>
    </div>
  </div>

app/views/handovers/delete.js.erb
$("#handover-modal").html("<%= escape_javascript(render 'delete') %>");
$("#handover-modal").modal("show");

app/views/handovers/edit.js.erb
$("#handover-modal").html("<%= escape_javascript(render 'edit') %>");
$("#handover-modal").modal("show");

app/views/handovers/index.html.erb
<div class="br-pageheader">
      <nav class="breadcrumb pd-0 mg-0 tx-12">
        
        <span class="breadcrumb-item active"><h3>Etats des lieux</h3></span>
      </nav>
    </div><!-- br-pageheader -->
<div class="br-pagebody">
  <div class="br-section-wrapper">
<div class="headers mg-b-20">
    <div class="left-content">
    </div>

    <div class="text-right">
        <%= link_to raw('<i class="fa fa-plus" aria-hidden="true"></i> Ajouter'), new_handover_path, class: "btn btn-primary tx-mont tx-medium tx-11 tx-uppercase pd-y-12 pd-x-25 tx-spacing-1", remote: true %>

    </div>

</div>


<table id="datatable1" class="table display responsive nowrap">
  

  <thead>
    <tr>
      <th>Type</th>
      <th>Reference</th>
      <th>Lease</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody class="handovers">
    <%= render "index"%>
  </tbody>
</table>
</div>
</div>
<div id="handover-modal" class="c-modal modal fade" data-backdrop="static"></div>

app/views/handovers/new.js.erb
$("#handover-modal").html("<%= escape_javascript(render 'new') %>");
$("#handover-modal").modal("show");

app/views/handovers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @handover.type %>
</p>

<p>
  <strong>Reference:</strong>
  <%= @handover.reference %>
</p>

<p>
  <strong>Lease:</strong>
  <%= @handover.lease %>
</p>

<p>
  <strong>Doors:</strong>
  <%= @handover.doors %>
</p>

<p>
  <strong>Windows:</strong>
  <%= @handover.windows %>
</p>

<p>
  <strong>Wall cover:</strong>
  <%= @handover.wall_cover %>
</p>

<p>
  <strong>Flooring:</strong>
  <%= @handover.flooring %>
</p>

<p>
  <strong>Ventilators:</strong>
  <%= @handover.ventilators %>
</p>

<p>
  <strong>Air conditioners:</strong>
  <%= @handover.air_conditioners %>
</p>

<p>
  <strong>Light bulbs:</strong>
  <%= @handover.light_bulbs %>
</p>

<p>
  <strong>Faucets:</strong>
  <%= @handover.faucets %>
</p>

<p>
  <strong>Showers:</strong>
  <%= @handover.showers %>
</p>

<p>
  <strong>Doorbell:</strong>
  <%= @handover.doorbell %>
</p>

<p>
  <strong>Ceiling:</strong>
  <%= @handover.ceiling %>
</p>

<p>
  <strong>Electricity:</strong>
  <%= @handover.electricity %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @handover.notes %>
</p>

<p>
  <strong>User:</strong>
  <%= @handover.user %>
</p>

<%= link_to 'Edit', edit_handover_path(@handover) %> |
<%= link_to 'Back', handovers_path %>