config/routes.rb
Rails.application.routes.draw do

  
  resources :rent_payments
  resources :permission_items
  resources :features
  resources :currencies
  resources :expenses do 
    get "delete"
  end
  resources :incomes do 
    get "delete"

    collection do  
        get "get_property_rent" => "incomes#get_property_rent"

    end

  end
  
  resources :payments do 
    get "delete"
  end
  
  resources :taxes do 
    get "delete"
  end
  resources :organizations do 
    get "delete"
  end
  resources :handovers do 
    get "delete"
  end
  resources :leases do 
    get "delete"

    collection do  
        get "get_available_properties" => "leases#get_available_properties"
        get "get_property_rent" => "leases#get_property_rent"
        get "get_properties_by_type" => "leases#get_properties_by_type"


    end
  end
  resources :mandates do 
    get "delete"

    collection do  
        get "get_properties" => "mandates#get_properties"
        get "get_properties_by_type" => "mandates#get_properties_by_type"

        get "get_property_rent" => "mandates#get_property_rent"

    end
    
  end

  resources :properties do 
    get "delete"
    
    collection do  
        get "get_landlord" => "properties#get_landlord"
        #get "get_prestation_amount" => "receipts#get_prestation_amount"

    end
    
  end
  resources :buildings do 
    get "delete"
  end
  resources :cities do 
    get "delete"
  end
  resources :tenants do 
    get "delete"
  end
  resources :landlords do 
    get "delete"
  end
  resources :landlord_types do 
    get "delete"
  end
  resources :tenant_types do 
    get "delete"
  end
  resources :property_types do 
    get "delete"
  end
  resources :profiles do 
    get "delete"
  end
  resources :services do 
    get "delete"
  end
  #devise_for :users
  resources :permissions do 
    get "delete"
  end
  resources :roles do 
    get "delete"
  end
  


  get "/dashboard" => "dashboard#index" , as: :dashboard
  get "/users"     => "custom_users#index", as: :all_users 
  get "/users/unregistered"     => "custom_users#unregistered", as: :unregistered_commission_percentage 
  post "/users/new"     => "custom_users#create", as: :create_user
  get "/users/new"     => "custom_users#new", as: :new_user
  get "/user/edit/:id" => "custom_users#edit", as: :edit_user
  patch "/user/update/:id" => "custom_users#update", as: :update_user
  delete "/user/destroy/:id" => "custom_users#destroy", as: :destroy_user
  get "/user/delete/:id" => "custom_users#delete", as: :delete_user
  
  get "/setup/admin" => "admin_setup#new", as: :new_admin
  post "/setup/admin/create" => "admin_setup#create", as: :create_admin


  get "/user/enable/:id" => "custom_users#get_enable", as: :get_enable_user_account
  post "/user/enable/:id" => "custom_users#post_enable", as: :post_enable_user_account
  get "/user/disable/:id" => "custom_users#get_disable", as: :get_disable_user_account
  post "/user/disable/:id" => "custom_users#post_disable", as: :post_disable_user_account


  devise_for :users, path: '', controllers: { 
    registrations: "users/registrations",
    confirmations: 'users/confirmations',
    passwords: "users/passwords",
    sessions: "users/sessions"
        
    }, 
    path_names: {
        sign_in: 'login', 
        sign_out: 'logout', 
        password: 'secret', 
        confirmation: 'verification', 
        unlock: 'unblock', 
        registration: 'signup', 
        sign_up: '' 
    }
   
    devise_scope :user do
      root to: "users/sessions#new"
      authenticated :user do
        root 'dashboard#index', as: :authenticated_root
      end
  
      unauthenticated do
        root 'users/sessions#new', as: :unauthenticated_root
      end
    end


    # Dynamic error pages
    get "/404", to: "errors#not_found"
    get "/422", to: "errors#unacceptable"
    get "/500", to: "errors#internal_error"


end

app/models/mandate.rb
# == Schema Information
#
# Table name: mandates
#
#  id                  :bigint           not null, primary key
#  property_type_id    :bigint
#  building_id         :bigint
#  property_id         :bigint
#  usage_type          :string
#  start_date          :datetime
#  end_date            :datetime
#  effective_date      :datetime
#  duration            :string
#  id_type             :string
#  id_number           :string
#  periodicity         :string
#  property_value      :float
#  commission_rate     :float
#  commission_amount   :float
#  property_tax_rate   :float
#  property_tax_amount :float
#  net_amount          :float
#  status              :string
#  notes               :text
#  user_id             :bigint
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Mandate < ApplicationRecord
  include SharedUtils::Generate

  before_save :generate_random_number_uid
  
  belongs_to :landlord, optional: true
  belongs_to :property, optional: true
  belongs_to :building, optional: true

  belongs_to :user
  
  #has_one :property, dependent: :destroy
  #has_one :building, dependent: :destroy

  #validates_uniqueness_of :re, presence: true, :scope => :building_id
  #validates :property_id, presence: true, uniqueness: true


end

app/controllers/mandates_controller.rb
class MandatesController < ApplicationController

  include FilterConcern
  
  before_action :authenticate_user!

  before_action :set_mandate, only: [:show, :edit, :update, :destroy]

  layout "dashboard"
  # GET /mandates
  # GET /mandates.json
  def index
    @mandates = Mandate.all
  end

  # GET /mandates/1
  # GET /mandates/1.json
  def show
  end

  # GET /mandates/new
  def new
    @property_types = PropertyType.all 
    @landlords = Landlord.all 
    @buildings = Building.all 
    @properties = Property.all
    @taxes = Tax.all
    @mandate = Mandate.new
  end

  # GET /mandates/1/edit
  def edit
    @property_types = PropertyType.all 
    @landlords = Landlord.all 
    @buildings = Building.all 
    @properties = Property.all
    @taxes = Tax.all
  end

  # POST /mandates
  # POST /mandates.json
  def create
    @mandate = current_user.mandates.build(mandate_params)

    puts "PROPERTY: #{@mandate.property_id}"
    @mandate.property_id = nil if @mandate.property_id == 0
    @mandate.building_id = nil if @mandate.building_id == 0

    @mandate.landlord_id = @mandate.property.present? ? @mandate.property.landlord_id : @mandate.building.landlord_id

    respond_to do |format|
      if @mandate.save
        @mandates = Mandate.all
        format.html { redirect_to @mandate, notice: 'Mandate was successfully created.' }
        format.json { render :show, status: :created, location: @mandate }
        format.js
      else
        format.html { render :new }
        format.json { render json: @mandate.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /mandates/1
  # PATCH/PUT /mandates/1.json
  def update
    respond_to do |format|
      if @mandate.update(mandate_params)
        @mandates = Mandate.all
        format.html { redirect_to @mandate, notice: 'Mandate was successfully updated.' }
        format.json { render :show, status: :ok, location: @mandate }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @mandate.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end


    def delete
      @mandate = Mandate.find(params[:mandate_id])
    end

  # DELETE /mandates/1
  # DELETE /mandates/1.json
  def destroy
    @mandate.destroy
    respond_to do |format|
      format.html { redirect_to mandates_url, notice: 'Mandate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mandate
      @mandate = Mandate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mandate_params
      params.require(:mandate).permit(:property_type_id, :building_id, :property_id, :usage_type, :start_date, :end_date, :effective_date, :duration, :id_type, :id_number, :periodicity, :property_value, :commission_rate, :commission_amount, :property_tax_rate, :property_tax_amount, :net_amount,  :notes)
    end
end

app/helpers/mandates_helper.rb
module MandatesHelper

	def property(id)
		Property.find(id)
	end
end

app/views/mandates/_create.js.erb
$("ul.errors").html("");
<% if @mandate.errors.any? %>
  <% @mandate.errors.full_messages.each do |message| %>
 
    $("ul.errors").append($('<div class="c-alert c-alert--danger" > ').html("<%= message.html_safe %> "));
  <% end %>
<% else %>
  $(".mandates").html("<%= escape_javascript(render 'index') %>");
  $("#mandate-modal").modal("hide");
 
<% end %>

app/views/mandates/_delete.html.erb
<!-- Modal -->

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header pd-y-20 pd-x-25">
            <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">Suppression</h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
      	<div class="modal-body">
  <ul class="errors"></ul>
  Etes-vous sûr de vouloir supprimer cet enregistrement?
  <p>
  Référence: <b> <%= @mandate.id %></b>
  </p>
  </div>
  <div class="modal-footer">
    <%= link_to "Non", "#", class: "btn btn-secondary tx-mont tx-medium tx-11 tx-uppercase pd-y-12 pd-x-25 tx-spacing-1", data: { dismiss: "modal" } %>
    <%= link_to "Oui", mandate_path(@mandate), method: :delete, remote: true, class: "btn btn-danger tx-mont tx-medium tx-11 tx-uppercase pd-y-12 pd-x-25 tx-spacing-1" %>
  </div>
  </div>
</div>

app/views/mandates/_edit.html.erb
<!-- Modal -->

  <div class="modal-dialog modal-lg">
    <div class="modal-content ">
      <div class="modal-header pd-y-20 pd-x-25">
            <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">Modification - Mandat</h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

<%= render 'form', mandate: @mandate %>
</div>
  </div>

app/views/mandates/_form.html.erb
<%= form_with(model: mandate, local: false) do |form| %>
  <div class="modal-body">
  
        <ul class="errors">
        </ul>

  

  <div class="row">
    <div class="form-group col-md-3  ">
      <%= form.label :property_type_id, "Type", class: "required" %>
      <%= form.collection_select(:property_type_id, @property_types, :id, :name, {prompt: "Sélectionner"}, class: "form-control ", style: "width: 100%", required: true) %> 
    </div>

   
    <div class="form-group col-md-4 buildings">
      <%= form.label :building_id, "Immeuble" %>
      <%= form.collection_select(:building_id, @buildings, :id, :reference, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%;") %> 
      
    </div>
   
    <div class="form-group col-md-5">
      <%= form.label :property_id, "Propriété", class: "required" %>
      <%= form.collection_select(:property_id, @properties, :id, :reference, {prompt: "Sélectionner"}, class: "form-control", style: "width: 100%") %> 
    </div> 
  </div>

  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <%= form.label :usage_type, "Usage", class: "required"  %>
        <%= form.select :usage_type, USAGE_TYPES, {prompt: "Sélectionner"}, class: "form-control" %>
      </div>
    </div>

  
    <div class="col-md-3">
      <div class="form-group">
        <%= form.label :start_date, "Date début", class: "required" %>
        <%= form.date_field :start_date, class: "form-control", required: true %>
      </div>
    </div>

    <div class="col-md-3">
      <div class="form-group">
        <%= form.label :end_date, "Date fin", class: "required" %>
        <%= form.date_field :end_date, class: "form-control", required: true %>
      </div>
    </div>

    <div class="col-md-3">

      <div class="form-group">
        <%= form.label :effective_date, "Date d'effet", class: "required" %>
        <%= form.date_field :effective_date, class: "form-control", required: true %>
      </div>
    </div>
  </div>

  

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :periodicity, "Périodicité", class: "required" %>
        <%= form.select :periodicity, PERIODICITY, {prompt: "Sélectionner"}, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :property_value, "Valeur", class: "required" %>
        <%= form.number_field :property_value, class: "form-control", lang: "fr", step: "0.01", value: (mandate.property_value.present? ? mandate.property_value : 0.0), min: "1", required: true %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :commission_rate, "Taux de commission (%)", class: "required" %>
        <%= form.number_field :commission_rate, class: "form-control",  lang: "fr", step: "0.01", value: (mandate.commission_rate.present? ? mandate.commission_rate : 0.0), min: "1", required: true %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :commission_amount, "Montant commission", class: "required" %>
        <%= form.number_field :commission_amount, class: "form-control", lang: "fr", step: "0.01", value: (mandate.commission_amount.present? ? mandate.commission_amount : 0.0), min: "1", required: true, readonly: true %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :property_tax_rate, "Taux taxe foncière (%)", class: "required" %>
        <%= form.collection_select(:property_tax_rate, @taxes, :rate, :name, {prompt: "Sélectionner"}, class: "form-control") %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :property_tax_amount, "Montant taxe foncière", class: "required" %>
        <%= form.number_field :property_tax_amount, class: "form-control", lang: "fr", step: "0.01", value: (mandate.property_tax_amount.present? ? mandate.property_tax_amount : 0.0), min: "1", required: true, readonly: true %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= form.label :notes, "Notes" %>
        <%= form.text_area :notes, class: "form-control", placeholder: "Notes" %>
      </div>
    </div>
  </div>

 

  </div><!-- modal body -->
     <div class="modal-footer">
            <%= link_to "Annuler", "#", class: "btn btn-secondary tx-mont tx-medium tx-11 tx-uppercase pd-y-12 pd-x-25 tx-spacing-1", data: {dismiss: "modal"} %>
            <%= form.submit "Enregistrer", class: "btn btn-primary tx-mont tx-medium tx-11 tx-uppercase pd-y-12 pd-x-25 tx-spacing-1",  "data-loading-text"=>"Loading...", autocomplete: "off" %>
    </div>
<% end %>

app/views/mandates/_index.html.erb
<% @mandates.each do |mandate| %>
      <tr>
        <td><%= mandate.created_at.strftime("%d/%m/%Y")  %></td>
        <td><%= mandate.building.reference if mandate.building_id   %></td>

        <td><%= mandate.property.reference if mandate.property_id   %></td>
        <td> <%= mandate.landlord.full_name  %></td>

        <td><%= mandate.usage_type %></td>
        <td>
            <div class="action-buttons">
                    <%= link_to raw('<i class="fa fa-pencil" aria-hidden="true"></i>
'), edit_mandate_path(mandate), title: "Modifier", remote: true %>




<%= link_to raw('<i class="fa fa-trash-o" aria-hidden="true"></i>
'), mandate_delete_path(mandate), remote: true, title: "Supprimer", class: "delete" %>
</div>
        </td>
      </tr>
    <% end %>

app/views/mandates/_new.html.erb
<!-- Modal -->

  <div class="modal-dialog modal-lg">
    <div class="modal-content ">
      <div class="modal-header pd-y-20 pd-x-25">
            <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">Nouveau - Mandat</h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

<%= render 'form', mandate: @mandate %>
</div>
  </div>

app/views/mandates/delete.js.erb
$("#mandate-modal").html("<%= escape_javascript(render 'delete') %>");
$("#mandate-modal").modal("show");

app/views/mandates/edit.js.erb
$("#mandate-modal").html("<%= escape_javascript(render 'edit') %>");
$("#mandate-modal").modal("show");

app/views/mandates/get_properties.js.erb
$('#mandate_property_id').html("<%= escape_javascript(options_for_select(@properties)) %>");

app/views/mandates/get_properties_by_type.js.erb
$('#mandate_property_id').html("<%= escape_javascript(options_for_select(@properties)) %>");

app/views/mandates/get_property_rent.js.erb
$('#mandate_property_value').val('<%= @property.rent_excluding_tax %>'); 

app/views/mandates/index.html.erb
<div class="br-pageheader">
      <nav class="breadcrumb pd-0 mg-0 tx-12">
        
        <span class="breadcrumb-item active"><h3>Mandats</h3></span>
      </nav>
    </div><!-- br-pageheader -->
<div class="br-pagebody">
  <div class="br-section-wrapper">
<div class="headers mg-b-20">
    <div class="left-content">
    </div>

    <div class="text-right">
        <%= link_to raw('<i class="fa fa-plus" aria-hidden="true"></i> Ajouter'), new_mandate_path, class: "btn btn-primary tx-mont tx-medium tx-11 tx-uppercase pd-y-12 pd-x-25 tx-spacing-1", remote: true %>

    </div>

</div>


<table id="datatable1" class="table display responsive nowrap">
  


  <thead>
    <tr>
      <th>Date</th>
      <th>Immeuble</th>
      <th>Propriété</th>
      <th>Propriétaire</th>
      <th>Usage</th>
      
      <th>Actions</th>
    </tr>
  </thead>

 <tbody class="mandates">
    <%= render "index"%>
  </tbody>
</table>




</div>
</div>
<div id="mandate-modal" class="modal fade" data-backdrop="static"></div>

app/views/mandates/new.js.erb
$("#mandate-modal").html("<%= escape_javascript(render 'new') %>");
$("#mandate-modal").modal("show");

app/views/mandates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Landlord:</strong>
  <%= @mandate.landlord %>
</p>

<p>
  <strong>Building:</strong>
  <%= @mandate.building_id %>
</p>

<p>
  <strong>Property:</strong>
  <%= @mandate.property_id %>
</p>

<p>
  <strong>Usage type:</strong>
  <%= @mandate.usage_type %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @mandate.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @mandate.end_date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @mandate.duration %>
</p>

<p>
  <strong>Id type:</strong>
  <%= @mandate.id_type %>
</p>

<p>
  <strong>Id number:</strong>
  <%= @mandate.id_number %>
</p>

<p>
  <strong>Periodicity:</strong>
  <%= @mandate.periodicity %>
</p>

<p>
  <strong>Property value:</strong>
  <%= @mandate.property_value %>
</p>

<p>
  <strong>Commission rate:</strong>
  <%= @mandate.commission_rate %>
</p>

<p>
  <strong>Commission amount:</strong>
  <%= @mandate.commission_amount %>
</p>

<p>
  <strong>Vat rate:</strong>
  <%= @mandate.vat_rate %>
</p>

<p>
  <strong>Net amount:</strong>
  <%= @mandate.net_amount %>
</p>

<p>
  <strong>Status:</strong>
  <%= @mandate.status %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @mandate.notes %>
</p>

<p>
  <strong>User:</strong>
  <%= @mandate.user %>
</p>

<%= link_to 'Edit', edit_mandate_path(@mandate) %> |
<%= link_to 'Back', mandates_path %>