config/routes.rb
Rails.application.routes.draw do

  
  resources :rent_payments
  resources :permission_items
  resources :features
  resources :currencies
  resources :expenses do 
    get "delete"
  end
  resources :incomes do 
    get "delete"

    collection do  
        get "get_property_rent" => "incomes#get_property_rent"

    end

  end
  
  resources :payments do 
    get "delete"
  end
  
  resources :taxes do 
    get "delete"
  end
  resources :organizations do 
    get "delete"
  end
  resources :handovers do 
    get "delete"
  end
  resources :leases do 
    get "delete"

    collection do  
        get "get_available_properties" => "leases#get_available_properties"
        get "get_property_rent" => "leases#get_property_rent"
        get "get_properties_by_type" => "leases#get_properties_by_type"


    end
  end
  resources :mandates do 
    get "delete"

    collection do  
        get "get_properties" => "mandates#get_properties"
        get "get_properties_by_type" => "mandates#get_properties_by_type"

        get "get_property_rent" => "mandates#get_property_rent"

    end
    
  end

  resources :properties do 
    get "delete"
    
    collection do  
        get "get_landlord" => "properties#get_landlord"
        #get "get_prestation_amount" => "receipts#get_prestation_amount"

    end
    
  end
  resources :buildings do 
    get "delete"
  end
  resources :cities do 
    get "delete"
  end
  resources :tenants do 
    get "delete"
  end
  resources :landlords do 
    get "delete"
  end
  resources :landlord_types do 
    get "delete"
  end
  resources :tenant_types do 
    get "delete"
  end
  resources :property_types do 
    get "delete"
  end
  resources :profiles do 
    get "delete"
  end
  resources :services do 
    get "delete"
  end
  #devise_for :users
  resources :permissions do 
    get "delete"
  end
  resources :roles do 
    get "delete"
  end
  


  get "/dashboard" => "dashboard#index" , as: :dashboard
  get "/users"     => "custom_users#index", as: :all_users 
  get "/users/unregistered"     => "custom_users#unregistered", as: :unregistered_commission_percentage 
  post "/users/new"     => "custom_users#create", as: :create_user
  get "/users/new"     => "custom_users#new", as: :new_user
  get "/user/edit/:id" => "custom_users#edit", as: :edit_user
  patch "/user/update/:id" => "custom_users#update", as: :update_user
  delete "/user/destroy/:id" => "custom_users#destroy", as: :destroy_user
  get "/user/delete/:id" => "custom_users#delete", as: :delete_user
  
  get "/setup/admin" => "admin_setup#new", as: :new_admin
  post "/setup/admin/create" => "admin_setup#create", as: :create_admin


  get "/user/enable/:id" => "custom_users#get_enable", as: :get_enable_user_account
  post "/user/enable/:id" => "custom_users#post_enable", as: :post_enable_user_account
  get "/user/disable/:id" => "custom_users#get_disable", as: :get_disable_user_account
  post "/user/disable/:id" => "custom_users#post_disable", as: :post_disable_user_account


  devise_for :users, path: '', controllers: { 
    registrations: "users/registrations",
    confirmations: 'users/confirmations',
    passwords: "users/passwords",
    sessions: "users/sessions"
        
    }, 
    path_names: {
        sign_in: 'login', 
        sign_out: 'logout', 
        password: 'secret', 
        confirmation: 'verification', 
        unlock: 'unblock', 
        registration: 'signup', 
        sign_up: '' 
    }
   
    devise_scope :user do
      root to: "users/sessions#new"
      authenticated :user do
        root 'dashboard#index', as: :authenticated_root
      end
  
      unauthenticated do
        root 'users/sessions#new', as: :unauthenticated_root
      end
    end


    # Dynamic error pages
    get "/404", to: "errors#not_found"
    get "/422", to: "errors#unacceptable"
    get "/500", to: "errors#internal_error"


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :authenticate_user!
	layout("dashboard")
	def index
		@properties = current_user.properties
		@buildings = current_user.buildings
		@leases = current_user.leases
		#@inquiry_forms = current_user.recipient_inquiry_forms
		#@ads = []
	end
	def show
	end
end

app/views/layouts/partials/dashboard/navs/_admin-nav.html.erb
<!-- ########## START: LEFT PANEL ########## -->

      <ul class="br-sideleft-menu">
        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Tableau de bord</span>'), dashboard_path, class: "br-menu-link #{current? "active", dashboard_path}" %>
        </li><!-- br-menu-item -->

        


        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-building tx-20"></i>
            <span class="menu-item-label">Biens</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Propriétés", properties_path, class: "sub-link #{current? "active", properties_path}" %>
            </li>
             <li class="sub-item">
                <%= link_to  "Immeubles", buildings_path, class: "sub-link" %>
            </li>
          </ul>
        </li>

        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-key tx-20"></i> <span class="menu-item-label">Locations</span>'), leases_path, class: "br-menu-link #{current? "active", leases_path}" %>
        </li>

        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-file-text-o tx-20"></i> <span class="menu-item-label">Mandats</span>'), mandates_path, class: "br-menu-link #{current? "active", mandates_path}" %>
        </li> 

        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-users tx-20"></i> <span class="menu-item-label">Locataires</span>'), tenants_path, class: "br-menu-link #{current? "active", tenants_path}" %>
        </li>
        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-user-secret tx-20"></i> <span class="menu-item-label">Propriétaires</span>'), landlords_path, class: "br-menu-link #{current? "active", landlords_path}" %>
        </li>

        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-check-square-o tx-20"></i> <span class="menu-item-label">Etats des lieux</span>'), handovers_path, class: "br-menu-link #{current? "active", handovers_path}" %>
        </li> 

        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-money tx-20"></i>
            <span class="menu-item-label">Comptabilité</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Paiements", incomes_path, class: "sub-link #{current? "active", incomes_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Dépenses", expenses_path, class: "sub-link #{current? "active", expenses_path}" %>
            </li>

             
          </ul>
        </li>

        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-bar-chart tx-20"></i>
            <span class="menu-item-label">Situations</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Paiements", incomes_path, class: "sub-link #{current? "active", incomes_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Dépenses", expenses_path, class: "sub-link #{current? "active", expenses_path}" %>
            </li>

             
          </ul>
        </li>


        

        
        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-cogs tx-20"></i>
            <span class="menu-item-label">Paramètres</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Utilisateurs", all_users_path, class: "sub-link #{current? "active", all_users_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Types de locataires", tenant_types_path, class: "sub-link #{current? "active", tenant_types_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Types de propriétaires", landlord_types_path, class: "sub-link #{current? "active", landlord_types_path}" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Types de propriétés", property_types_path, class: "sub-link #{current? "active", property_types_path}" %>
            </li>

             <li class="sub-item">
                <%= link_to  "Taxes", taxes_path, class: "sub-link #{current? "active", taxes_path}" %>
            </li>
             
          </ul>
        </li>
       
      </ul><!-- br-sideleft-menu -->

      
       
        
      </div><!-- info-list -->

    <!-- ########## END: LEFT PANEL ########## -->

app/views/layouts/partials/dashboard/navs/_superadmin-nav.html.erb
    <h5 class="sidenav-heading">Menu</h5>
        <ul id="side-main-menu" class="side-menu list-unstyled">                 
            <li>
				<%= link_to raw('<i class="fa fa-line-chart" aria-hidden="true"></i>Tableau de bord'), dashboard_path %>
			</li>
			<li>
				<%= link_to raw('<i class="fa fa-balance-scale" aria-hidden="true"></i>
Crédits'), credits_path %>
			</li>
			
			<li>
				<a href="#commissiondropdownDropdown" aria-expanded="false" data-toggle="collapse"> 
					<i class="fa fa-money" aria-hidden="true"></i>Commissions</a>
                <ul id="commissiondropdownDropdown" class="collapse list-unstyled ">
                    <li><%= link_to raw('<i class="fa fa-address-book-o" aria-hidden="true"></i>Apporteurs'), contributors_commissions_path %>
                    </li>
                    <li>
                        <%= link_to raw('<i class="fa fa-address-book" aria-hidden="true"></i> Producteurs'), producers_commissions_path %>
                    </li>
                    <li>
                        <%= link_to raw('<i class="fa fa-university" aria-hidden="true"></i> Banques'), banks_commissions_path %>
                    </li>
                </ul>
            </li>
				
           
            <li>
                <%= link_to raw('<i class="fa fa-building-o" aria-hidden="true"></i>Banques'), banks_path %>
            </li>
				<% if is_admin? || is_superadmin? %>
					<li>
						<a href="#exampledropdownDropdown" aria-expanded="false" data-toggle="collapse"> <i class="fa fa-cogs" aria-hidden="true"></i>
						Paramètres</a>
						<ul id="exampledropdownDropdown" class="collapse list-unstyled">
							<% if is_admin? || is_superadmin? %>
								<li>
									<%= link_to raw('<i class="fa fa-user" aria-hidden="true"></i> Utilisateurs'), all_users_path %>
								</li>
								
							
						
                            <li>
                                <%= link_to raw('<i class="fa fa-envelope" aria-hidden="true"></i>Config. messagerie'), mail_settings_path %>
                            </li>
					<% end %>
				</ul>
			</li>
		<% end %>
    </ul>

   

app/views/layouts/partials/dashboard/navs/_superuser-nav.html.erb
    <h5 class="sidenav-heading">Menu</h5>
        <ul id="side-main-menu" class="side-menu list-unstyled">                 
            <li>
				<%= link_to raw('<i class="fa fa-line-chart" aria-hidden="true"></i>Tableau de bord'), dashboard_path %>
			</li>
			<li>
				<%= link_to raw('<i class="fa fa-balance-scale" aria-hidden="true"></i>
Crédits'), credits_path %>
			</li>
			
			<li>
				<a href="#commissiondropdownDropdown" aria-expanded="false" data-toggle="collapse"> 
					<i class="fa fa-money" aria-hidden="true"></i>Commissions</a>
                <ul id="commissiondropdownDropdown" class="collapse list-unstyled ">
                    <li><%= link_to raw('<i class="fa fa-address-book-o" aria-hidden="true"></i>Apporteurs'), contributors_commissions_path %>
                    </li>
                    <li>
                        <%= link_to raw('<i class="fa fa-address-book" aria-hidden="true"></i> Producteurs'), producers_commissions_path %>
                    </li>
                    <li>
                        <%= link_to raw('<i class="fa fa-university" aria-hidden="true"></i> Banques'), banks_commissions_path %>
                    </li>
                </ul>
            </li>
				
           
            <li>
                <%= link_to raw('<i class="fa fa-building-o" aria-hidden="true"></i>Banques'), banks_path %>
            </li>
				<% if is_admin? || is_superadmin? %>
					<li>
						<a href="#exampledropdownDropdown" aria-expanded="false" data-toggle="collapse"> <i class="fa fa-cogs" aria-hidden="true"></i>
						Paramètres</a>
						<ul id="exampledropdownDropdown" class="collapse list-unstyled">
							<% if is_admin? || is_superadmin? %>
								<li>
									<%= link_to raw('<i class="fa fa-user" aria-hidden="true"></i> Utilisateurs'), all_users_path %>
								</li>
								
							
						
                            <li>
                                <%= link_to raw('<i class="fa fa-envelope" aria-hidden="true"></i>Config. messagerie'), mail_settings_path %>
                            </li>
					<% end %>
				</ul>
			</li>
		<% end %>
    </ul>

   